### ISSUE TITLE
Reminder sent after removed as reviewer

### ISSUE THREAD

**Issue by ddgenome** [atomist-skills/pull-request-reminder-skill#136]
I was receiving reminders about a PR, https://github.com/atomist-skills/skill/pull/183 , so I removed myself as a reviewer, but this skill still sends me reminders about the PR.

**Comment by cdupuis** [comment]
You are still assigned to a requested review on the mentioned pull request per our GraphQL model. I guess we could consider this a bug in the ingestion of the corresponding GitHub event.

**Comment by ddgenome** [comment]
I'll open up a ticket there.
